<?php

namespace UsuariosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository {

    public function findAllOrderedByPuntos() {
        $query = $this->createQueryBuilder('cliente')
                ->orderBy('cliente.puntosAcumulados', 'DESC')
                ->getQuery();

        return $query->getResult();
    }

}
