<?php

namespace Proxies\__CG__\VentasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Venta extends \VentasBundle\Entity\Venta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'id', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'fecha', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'valorTotal', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'tipoVenta', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'puntosVenta', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'mesa', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'personasPorMesa', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'detalles', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'empleado', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'cliente');
        }

        return array('__isInitialized__', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'id', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'fecha', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'valorTotal', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'tipoVenta', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'puntosVenta', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'mesa', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'personasPorMesa', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'detalles', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'empleado', '' . "\0" . 'VentasBundle\\Entity\\Venta' . "\0" . 'cliente');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Venta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTotal($valorTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTotal', array($valorTotal));

        return parent::setValorTotal($valorTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTotal', array());

        return parent::getValorTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoVenta($tipoVenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoVenta', array($tipoVenta));

        return parent::setTipoVenta($tipoVenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoVenta', array());

        return parent::getTipoVenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntosVenta($puntosVenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntosVenta', array($puntosVenta));

        return parent::setPuntosVenta($puntosVenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntosVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntosVenta', array());

        return parent::getPuntosVenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesa($mesa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesa', array($mesa));

        return parent::setMesa($mesa);
    }

    /**
     * {@inheritDoc}
     */
    public function getMesa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesa', array());

        return parent::getMesa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonasPorMesa($personasPorMesa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonasPorMesa', array($personasPorMesa));

        return parent::setPersonasPorMesa($personasPorMesa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonasPorMesa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonasPorMesa', array());

        return parent::getPersonasPorMesa();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetalle(\VentasBundle\Entity\DetalleVenta $detalles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetalle', array($detalles));

        return parent::addDetalle($detalles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetalle(\VentasBundle\Entity\DetalleVenta $detalles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetalle', array($detalles));

        return parent::removeDetalle($detalles);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalles', array());

        return parent::getDetalles();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpleado(\UsuariosBundle\Entity\Empleado $empleado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpleado', array($empleado));

        return parent::setEmpleado($empleado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpleado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpleado', array());

        return parent::getEmpleado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\UsuariosBundle\Entity\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

}
