usuarios_cliente:
    resource: "@UsuariosBundle/Controller/ClienteController.php"
    type:     annotation

jornadas_laborales:
    resource: "@JornadasLaboralesBundle/Controller/"
    type:     annotation
    prefix:   /

costos:
    resource: "@CostosBundle/Controller/"
    type:     annotation
    prefix:   /

usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /

inventario:
    resource: "@InventarioBundle/Controller/"
    type:     annotation
    prefix:   /

ventas:
    resource: "@VentasBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"