<?php

namespace VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleVentaRepository extends EntityRepository
{
}
