<?php

namespace VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaRepository extends EntityRepository {

    public function findVentasMes($fechaInicial, $fechaFinal) {
        $query = $this->createQueryBuilder('venta')
                ->where('venta.fecha BETWEEN :inicial AND :final')
                ->setParameter('inicial', $fechaInicial)
                ->setParameter('final', $fechaFinal)
                ->getQuery();

        return $query->getResult();
    }

}
