<?php

namespace CostosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CostoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostoRepository extends EntityRepository
{
    public function findCostosIntervalo($fechaInicial, $fechaFinal) {
        $query = $this->createQueryBuilder('costo')
                ->where('costo.fecha BETWEEN :inicial AND :final')
                ->setParameter('inicial', $fechaInicial)
                ->setParameter('final', $fechaFinal)
                ->getQuery();

        return $query->getResult();
    }
}
