<?php

namespace CostosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CostoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostoRepository extends EntityRepository
{
}
