<?php

namespace JornadasLaboralesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TurnosLaboralesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoLaboralRepository extends EntityRepository
{
}
