<?php

namespace InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IngresoMateriaPrimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngresoMateriaPrimaRepository extends EntityRepository
{
}
