<?php

namespace InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MateriaPrimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriaPrimaRepository extends EntityRepository {

    public function findAllOrderedByNombre() {
        $query = $this->createQueryBuilder('materia')
                        ->orderBy('materia.nombre', 'ASC')
                        ->getQuery();
        
        return $query->getResult();
    }

}
