<?php

namespace InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository {

    public function findAllTipoOrderedByNombre($id) {
        $query = $this->createQueryBuilder('Producto')->where(Producto . TipoProducto === $id)->orderBy('Producto.nombre', 'ASC')->getQuery();
        return $query->getResult();
    }

}
