<?php

namespace InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProductoRepository extends EntityRepository {

    public function findAllOrderedByNombre() {
        $query = $this->createQueryBuilder('TipoProducto')->orderBy('TipoProducto.nombre', 'ASC')->getQuery();
        return $query->getResult();
    }

}
